config/routes.rb
Rails.application.routes.draw do

   resources :categories
   resources :itemtypes
   resources :mainpages do
    member do
      post 'populate_sub_category'
    end
   end

   root 'itemtypes#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :item_types, :class_name => 'Itemtype'
  validates :itemname, presence: true
end

app/models/itemtype.rb
class Itemtype < ActiveRecord::Base
  belongs_to :category
end

app/models/mainpage.rb
class Mainpage < ActiveRecord::Base
  belongs_to :category
  belongs_to :itemtype
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def new
		@category=Category.new
	end

	def create
		@category=Category.new(category_params)
		if @category.save
		   redirect_to categories_path
	    else
	    	render 'new'
	    end
	end

	def index
		@categories = Category.all
	end

	def show
		@category=Category.find(params[:id])
	end

	private
	def category_params
		params.require(:category).permit(:itemname)
	end
end

app/controllers/itemtypes_controller.rb
class ItemtypesController < ApplicationController
	def new
		@itemtype=Itemtype.new
	end

	def create
		
		@itemtype=Itemtype.new(item_params)
		@itemtype.save
		redirect_to itemtypes_path

	end

	def show
		@itemtype=ItemType.find(params[:id])
	end

	def index
		@itemtype=Itemtype.all
	end
     
     private 
     def item_params
     	params.require(:itemtypes).permit(:itemtypename,:amount,:category_id)
     end

end

app/controllers/mainpages_controller.rb
class MainpagesController < ApplicationController
	def new

	end

  def populate_sub_category
    @category = Category.find_by_id params[:id]
    @item_types = @category.item_types
  end
  #/mainpages/:id/populate_sub_category


end

app/helpers/application_helper.rb
module ApplicationHelper
	 def get_course
    Category.all.collect {|course| [course.itemname, course.id]}
  end

  def get_items
     Itemtype.all.collect {|items| [items.itemtypename, items.id]}
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/itemtypes_helper.rb
module ItemtypesHelper
end

app/helpers/mainpages_helper.rb
module MainpagesHelper
end

app/views/categories/index.html.erb
<table>

  <% @category.each do |s| %>
    <tr>
      <td><%= s.itemname %></td>

    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<center>
	<%=form_for :categories, :url =>categories_path, :method => "post" do |f| %>
	<table>
		<tr>
			<td><%=f.label :ItemName %></td>
			<td><%=f.text_field :itemname%></td>
		</tr>
		<tr>
			<td><%=f.submit :Save %></td>
		</tr>
	</table>
	
	<% end %>
</center>

app/views/categories/show.html.erb
<%=@category.itemname%>

app/views/itemtypes/index.html.erb
<table>
<tr>
	<td>Item Name</td>
	<td>Amount</td>
	<td>Category_Id</td>
</tr>
  <% @itemtype.each do |s| %>
    <tr>
      <td><%= s.itemtypename %></td>
      <td><%= s.amount %></td>
      <td><%=s.category_id%></td>
    </tr>
  <% end %>
</table>

app/views/itemtypes/new.html.erb
<center>
	<%=form_for :itemtypes, :url => itemtypes_path, :method => "post" do |f| %>
	<table>
	    <tr>
            <td><%=f.label :ItemName %></td>
	    	<td><%= f.select :category_id, get_course, {},:class => "form-control"%></td>
	    </tr>
		<tr>
			<td><%=f.label :ItemTypeName %></td>
			<td><%=f.text_field :itemtypename %></td>
		</tr>
		<tr>
			<td><%=f.label :Amount%></td>
			<td><%=f.text_field :amount%></td>
		</tr>
		<tr>
			<td><%=f.submit :Save%></td>
		</tr>
		
	</table>
	<% end %>
</center>

app/views/itemtypes/show.html.erb
<%=@itemtypes.amount%>
<%=@itemtypes.category_id%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HotelManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mainpages/new.html.erb
<center>
<%= form_for :mainpages, :url => mainpages_path, :method => "post" do |f| %>

	<table>

		<tr>
        <td><%=f.label :Categories %></td>
	    	<td><%= f.select :category_id, get_course, {},:class => "form-control",:id =>"category"%></td>
	    </tr>
	    <tr>
          <td><%=f.label :ItemType %></td>
	    	<td class='js-sub-items'><%= f.select :itemtype_id, get_items, {},:class => "form-control", :id => "js-items" %></td>
	    	<td><%= f.label :Quantity%></td>
	    	<td><%= f.text_field :quantity%></td>
	    	<td><%= f.button :Add%></td>
	    </tr>
		<tr>
			<td><%= f.label :TotalAmount%></td>
			<td><%= f.text_field :total_amount %></td>
		</tr>
		<tr>
			<td><%= f.submit :GenerateBill%></td>
		</tr>
<% end %>

</center>

app/views/mainpages/populate_sub_category.js.erb
$('.js-sub-items').html("<%= escape_javascript(select_tag 'mainpages[itemtype_id]', options_for_select(@item_types.map { |item| [item.itemtypename, item.id] }), :class => 'form-control', :id => 'js-items' ) %>");